version: '2'
volumes:
    config:
    resin-data:
services:
  homeassistant:
    image: "homeassistant/raspberrypi2-homeassistant:stable"
    ports:
      - 8123:8123
    privileged: true
    volumes:
      - 'config:/config'
    restart: always
    devices:
      - "/dev:/dev"
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave"
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - 1883:1883
    restart: always
  hass-configurator:
    image: causticlab/hass-configurator-docker:arm
    restart: always
    ports:
      - 3218:3218
    volumes:
      - 'config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config
  supervisor:
    image: homeassistant/armhf-hassio-supervisor
    #ports:
     # - 80:80
    volumes:
      - 'config:/data'
  node-red:
    build: ./node-red
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - 80:80
